### ISSUE TITLE
Add Support for Bing

### ISSUE THREAD

**Issue by MercuryXIII** [mozilla/voicefill#155] opened 2017-08-05 13:48 UTC

**Comment by marwendoukh** [comment] 2017-09-01 00:37
I think we need to close this issue since the PR has been merged

**Comment by SoftVision-CarmenFat** [comment] 2017-09-14 12:46
Hi all,
	
- I navigated today on https://www.bing.com/ but wasn't able to see the "microphone" button.
- Tested this using latest Nightly 57.0a1 (2017-09-13) , Beta 56.0b11 and Release 55.0.3 across platforms (Windows 10 x64, Ubuntu 16.04 x64 and macOS 10.12).

@marwendoukh can you please take a look at this?

![bing no icon](https://user-images.githubusercontent.com/26000308/30430366-ae8cc0be-9963-11e7-9506-51728c570590.gif)

**Comment by marwendoukh** [comment] 2017-09-14 20:40
@SoftVision-CarmenFat Thank you for submitting the issue .
 Sorry I have a problem with my Nightly , I could not unfortunately do the tests at the moment, I'll try to reproduce this as soon as the Nightly's problem will be solved.
Thanks

**Comment by marwendoukh** [comment] 2017-09-19 19:32
I still have the same issue with installing and testing the Voice fill web extension , anyone else has the same issue ?

**Closed** 2018-10-24 14:35 UTC
Labels: coverage
